# This is a basic workflow to help you get started with Actions

name: pizerow-dev-build

# Controls when the workflow will run
on:
  pull_request:
    types: [labeled, synchronize]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - run: pwd
      - run: which python3
      - run: python3 --version
      - run: which pip3 || true
      - run: pip3 --version || true
      - run: pip3 freeze || true
      - run: python3 -m pip --version || true
      - run: python3 -m venv tmp-venv
      - run: |
          . tmp-venv/bin/activate
          which python
          python --version
          python -m ensurepip --upgrade
          which pip
          pip install --upgrade pip
          pip freeze
          pip install wheel
          pip install bluezero pybleno pyserial gpiozero pymemcache RPi.GPIO grpcio
          deactivate

      - name: Build opentrickler_dev_defconfig
        run: |
          pwd
          ls -al
          whoami
          make opentrickler_dev_defconfig
          make -j10
          ls -al
          ls -al output/images/
